'use client'

import { useRouter } from 'next/navigation'
import { LucideArrowLeft, LucideShieldCheck } from 'lucide-react'
import { AnimateOnScroll } from '@/components/AnimateOnScroll'

export default function PrivacyPage() {
    const router = useRouter()

    return (
        <div className="min-h-screen py-12 px-4 sm:px-6 lg:px-8 bg-transparent">
            <div className="max-w-4xl mx-auto space-y-8">
                {/* Back Button */}
                <AnimateOnScroll delay={75}>
                    <button
                        onClick={() => router.back()}
                        className="group flex items-center gap-2 text-white/70 hover:text-white font-bold transition-all"
                    >
                        <LucideArrowLeft className="h-5 w-5 transition-transform group-hover:-translate-x-1" />
                        Go Back
                    </button>
                </AnimateOnScroll>

                {/* Content Card */}
                <AnimateOnScroll delay={150}>
                    <div className="glass-card overflow-hidden">
                        <div className="p-8 md:p-12">
                            <div className="flex items-center gap-4 mb-8">
                                <div className="p-3 bg-blue-100 rounded-2xl">
                                    <LucideShieldCheck className="h-8 w-8 text-blue-600" />
                                </div>
                                <div>
                                    <h1 className="text-3xl font-black uppercase tracking-tight text-gray-900">Privacy Policy</h1>
                                    <p className="text-sm text-gray-500 font-medium">Last updated: {new Date().toLocaleDateString()}</p>
                                </div>
                            </div>

                            <div className="space-y-12 text-gray-600 leading-relaxed">
                                <AnimateOnScroll>
                                    <section>
                                        <h2 className="text-xl font-bold text-gray-900 mb-3 flex items-center gap-2">
                                            <span className="h-6 w-1 bg-blue-500 rounded-full"></span>
                                            1. Information We Collect
                                        </h2>
                                        <p>
                                            We collect information you provide directly to us when creating an account, such as your name, email address, and your child's name.
                                            We also store session reports and progress data generated by Senseis during their training sessions.
                                        </p>
                                    </section>
                                </AnimateOnScroll>

                                <AnimateOnScroll>
                                    <section>
                                        <h2 className="text-xl font-bold text-gray-900 mb-3 flex items-center gap-2">
                                            <span className="h-6 w-1 bg-blue-500 rounded-full"></span>
                                            2. How We Use Your Information
                                        </h2>
                                        <p>
                                            We use the information we collect to provide, maintain, and improve the Dojo Hub service,
                                            to communicate with you about your child's progress, and to ensure a safe and effective learning environment for our ninjas.
                                        </p>
                                    </section>
                                </AnimateOnScroll>

                                <AnimateOnScroll>
                                    <section>
                                        <h2 className="text-xl font-bold text-gray-900 mb-3 flex items-center gap-2">
                                            <span className="h-6 w-1 bg-blue-500 rounded-full"></span>
                                            3. Data Security
                                        </h2>
                                        <p>
                                            Protecting your data is our top priority. We implement industry-standard security measures to protect your personal information.
                                            While we strive for absolute security, please remember that no method of transmission over the Internet is 100% secure.
                                        </p>
                                    </section>
                                </AnimateOnScroll>

                                <AnimateOnScroll>
                                    <section>
                                        <h2 className="text-xl font-bold text-gray-900 mb-3 flex items-center gap-2">
                                            <span className="h-6 w-1 bg-blue-500 rounded-full"></span>
                                            4. Sharing of Information
                                        </h2>
                                        <p>
                                            We respect your privacy. We do not sell your personal information. Information is only shared with third-party providers (e.g., Supabase)
                                            necessary to operate the service or when legally required to do so.
                                        </p>
                                    </section>
                                </AnimateOnScroll>

                                <AnimateOnScroll>
                                    <section>
                                        <h2 className="text-xl font-bold text-gray-900 mb-3 flex items-center gap-2">
                                            <span className="h-6 w-1 bg-blue-500 rounded-full"></span>
                                            5. Children's Privacy
                                        </h2>
                                        <p>
                                            This service is built for parents and guardians. We do not knowingly collect personal information directly from children under 13
                                            without explicit parental consent, which is provided when you create your account.
                                        </p>
                                    </section>
                                </AnimateOnScroll>

                                <AnimateOnScroll>
                                    <section className="pt-8 border-t border-gray-100 mt-12">
                                        <h2 className="text-xl font-bold text-gray-900 mb-3">6. Contact Us</h2>
                                        <p>
                                            Transparency is key to our Dojo. If you have any questions about this Privacy Policy, please reach out to your Dojo Director.
                                        </p>
                                    </section>
                                </AnimateOnScroll>
                            </div>
                        </div>
                    </div>
                </AnimateOnScroll>

                {/* Footer simple */}
                <AnimateOnScroll delay={300} bleed={true}>
                    <p className="text-center text-white/40 text-xs">
                        &copy; {new Date().getFullYear()} Dojo Hub. Keeping your data safe.
                    </p>
                </AnimateOnScroll>
            </div>
        </div>
    )
}
